packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: ^5.9.0
  "@types/node": ^20.19.0
  eslint: ^9.39.0
  prettier: ^3.8.0
  "@ai-sdk/openai": ^3.0.0
  drizzle-orm: ^0.45.0
  ioredis: ^5.11.0
  zod: ^4.0.0
